import BinarySearchTree from './BinarySearchTree.js'
import PriorityQueue from './PriorityQueue.js'

export const runTestBST = () => {
  const bst = new BinarySearchTree()

  console.log('------ BinarySearchTree ------')
  console.log(bst)
  const node1 = bst.insert({ key: 8, value: 123 })
  bst.insert({ key: 765, value: 456 })
  bst.insert({ key: 5, value: 65 })
  bst.insert({ key: 18, value: 123 })
  const node2 = bst.insert({ key: 9, value: 123 })
  console.log(bst)

  console.log('------ printAllBy("bft") ------')
  bst.printAllBy('bft')
  console.log('------ printAllBy("preOrder") ------')
  bst.printAllBy('preOrder')
  console.log('------ printAllBy("inOrder") ------')
  bst.printAllBy('inOrder')
  console.log('------ printAllBy("postOrder") ------')
  bst.printAllBy('postOrder')

  console.log('------ search(123) ------')
  console.log(bst.search(123))
  console.log('------ search(765) ------')
  console.log(bst.search(765))
  console.log('------ search(8) ------')
  console.log(bst.search(8))
  console.log('------ findNode(8) ------')
  console.log(bst.findNode(8))

  console.log('------ searchFrom(node1, 9) ------')
  console.log(bst.searchFrom(node1, 9))
  console.log('------ searchFrom(node2, 8) ------')
  console.log(bst.searchFrom(node2, 8))

  console.log('------ getListArrBy(inOrder) ------')
  console.log(bst.getListArrBy('inOrder'))
  console.log('------ getItemArrBy(inOrder) ------')
  console.log(bst.getItemArrBy('inOrder'))
}

export const runTestPQ = () => {
  const pq = new PriorityQueue()

  const toEnqueue = (item) => pq.enqueue(item, { isLog: true })

  console.log('------ PriorityQueue ------')
  console.log(pq)
  console.log('------ enqueue({ name: "Meme" }) ------')
  toEnqueue({ name: 'Meme' })
  console.log(pq.queue)
  console.log('------ enqueue({ priority: 3, name: "Mike" }) ------')
  toEnqueue({ priority: 3, name: 'Mike' })
  console.log('------ enqueue({ priority: 2, name: "Vicky" }) ------')
  toEnqueue({ priority: 2, name: 'Vicky' })
  console.log('------ enqueue({ priority: 5, name: "Wendy" }) ------')
  toEnqueue({ priority: 5, name: 'Wendy' })
  console.log('------ enqueue({ priority: 1, name: "Lisa" }) ------')
  toEnqueue({ priority: 1, name: 'Lisa' })
  console.log('------ enqueue({ priority: 9, name: "Bossy" }) ------')
  toEnqueue({ priority: 9, name: 'Bossy' })
  console.log('------ enqueue({ priority: 2, name: "Bo" }) ------')
  toEnqueue({ priority: 2, name: 'Bo' })
  console.log('------ enqueue({ priority: 6, name: "Lulu" }) ------')
  toEnqueue({ priority: 6, name: 'Lulu' })
  console.log('------ enqueue({ priority: 4, name: "Ray" }) ------')
  toEnqueue({ priority: 4, name: 'Ray' })
  console.log(pq.queue)
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log('------ enqueue({ priority: 9, name: "Boss" }) ------')
  toEnqueue({ priority: 9, name: 'Boss' })
  console.log('------ enqueue({ name: "Lala" }) ------')
  toEnqueue({ name: 'Lala' })
  console.log(pq.queue)
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log('------ dequeue ------')
  console.log(pq.dequeue())
  console.log(pq.queue)
}
